// Static metadata for each book — keys match exact KJV_books.name from the DB.
export interface BookMeta {
  author: string;
  location: string;
  date: string; // circa date or range
}

export const BOOK_META: Record<string, BookMeta> = {
  // ── Old Testament ──────────────────────────────────────────────────────────
  "Genesis":          { author: "Moses",                  location: "Sinai wilderness",    date: "c. 1445–1405 BC" },
  "Exodus":           { author: "Moses",                  location: "Sinai wilderness",    date: "c. 1445–1405 BC" },
  "Leviticus":        { author: "Moses",                  location: "Sinai wilderness",    date: "c. 1445–1405 BC" },
  "Numbers":          { author: "Moses",                  location: "Sinai / Moab",        date: "c. 1445–1405 BC" },
  "Deuteronomy":      { author: "Moses",                  location: "Plains of Moab",      date: "c. 1406 BC"      },
  "Joshua":           { author: "Joshua",                 location: "Canaan",              date: "c. 1405–1385 BC" },
  "Judges":           { author: "Samuel (trad.)",         location: "Israel",              date: "c. 1050–1000 BC" },
  "Ruth":             { author: "Samuel (trad.)",         location: "Israel",              date: "c. 1050–1000 BC" },
  "I Samuel":         { author: "Samuel / Nathan / Gad",  location: "Israel",              date: "c. 1050–1000 BC" },
  "II Samuel":        { author: "Nathan / Gad",           location: "Israel",              date: "c. 1000–960 BC"  },
  "I Kings":          { author: "Jeremiah (trad.)",       location: "Judah",               date: "c. 960–560 BC"   },
  "II Kings":         { author: "Jeremiah (trad.)",       location: "Judah",               date: "c. 850–560 BC"   },
  "I Chronicles":     { author: "Ezra (trad.)",           location: "Jerusalem",           date: "c. 450–400 BC"   },
  "II Chronicles":    { author: "Ezra (trad.)",           location: "Jerusalem",           date: "c. 450–400 BC"   },
  "Ezra":             { author: "Ezra",                   location: "Jerusalem",           date: "c. 457–444 BC"   },
  "Nehemiah":         { author: "Nehemiah",               location: "Jerusalem",           date: "c. 445–420 BC"   },
  "Esther":           { author: "Mordecai (trad.)",       location: "Persia",              date: "c. 480–470 BC"   },
  "Job":              { author: "Unknown",                location: "Unknown",             date: "c. 2000–1500 BC" },
  "Psalms":           { author: "David et al.",           location: "Israel",              date: "c. 1000–400 BC"  },
  "Proverbs":         { author: "Solomon et al.",         location: "Jerusalem",           date: "c. 950–700 BC"   },
  "Ecclesiastes":     { author: "Solomon (trad.)",        location: "Jerusalem",           date: "c. 940–935 BC"   },
  "Song of Solomon":  { author: "Solomon",                location: "Jerusalem",           date: "c. 960 BC"       },
  "Isaiah":           { author: "Isaiah",                 location: "Jerusalem",           date: "c. 740–700 BC"   },
  "Jeremiah":         { author: "Jeremiah",               location: "Judah / Egypt",       date: "c. 627–580 BC"   },
  "Lamentations":     { author: "Jeremiah",               location: "Jerusalem",           date: "c. 586 BC"       },
  "Ezekiel":          { author: "Ezekiel",                location: "Babylon",             date: "c. 593–571 BC"   },
  "Daniel":           { author: "Daniel",                 location: "Babylon",             date: "c. 605–530 BC"   },
  "Hosea":            { author: "Hosea",                  location: "Israel",              date: "c. 755–725 BC"   },
  "Joel":             { author: "Joel",                   location: "Judah",               date: "c. 835–796 BC"   },
  "Amos":             { author: "Amos",                   location: "Israel",              date: "c. 760–755 BC"   },
  "Obadiah":          { author: "Obadiah",                location: "Judah",               date: "c. 586–580 BC"   },
  "Jonah":            { author: "Jonah",                  location: "Israel",              date: "c. 793–753 BC"   },
  "Micah":            { author: "Micah",                  location: "Judah",               date: "c. 735–700 BC"   },
  "Nahum":            { author: "Nahum",                  location: "Judah",               date: "c. 663–612 BC"   },
  "Habakkuk":         { author: "Habakkuk",               location: "Judah",               date: "c. 612–589 BC"   },
  "Zephaniah":        { author: "Zephaniah",              location: "Judah",               date: "c. 640–621 BC"   },
  "Haggai":           { author: "Haggai",                 location: "Jerusalem",           date: "c. 520 BC"       },
  "Zechariah":        { author: "Zechariah",              location: "Jerusalem",           date: "c. 520–480 BC"   },
  "Malachi":          { author: "Malachi",                location: "Jerusalem",           date: "c. 430 BC"       },
  // ── New Testament ──────────────────────────────────────────────────────────
  "Matthew":              { author: "Matthew",              location: "Antioch / Judea",   date: "c. AD 50–70"  },
  "Mark":                 { author: "John Mark",            location: "Rome / Alexandria", date: "c. AD 55–65"  },
  "Luke":                 { author: "Luke",                 location: "Rome / Caesarea",   date: "c. AD 60–80"  },
  "John":                 { author: "John the Apostle",     location: "Ephesus",           date: "c. AD 85–95"  },
  "Acts":                 { author: "Luke",                 location: "Rome / Caesarea",   date: "c. AD 62–80"  },
  "Romans":               { author: "Paul",                 location: "Corinth",           date: "c. AD 57"     },
  "I Corinthians":        { author: "Paul",                 location: "Ephesus",           date: "c. AD 55"     },
  "II Corinthians":       { author: "Paul",                 location: "Macedonia",         date: "c. AD 55–56"  },
  "Galatians":            { author: "Paul",                 location: "Antioch / Corinth", date: "c. AD 48–55"  },
  "Ephesians":            { author: "Paul",                 location: "Rome",              date: "c. AD 60–62"  },
  "Philippians":          { author: "Paul",                 location: "Rome",              date: "c. AD 62"     },
  "Colossians":           { author: "Paul",                 location: "Rome",              date: "c. AD 60–62"  },
  "I Thessalonians":      { author: "Paul",                 location: "Corinth",           date: "c. AD 51"     },
  "II Thessalonians":     { author: "Paul",                 location: "Corinth",           date: "c. AD 51–52"  },
  "I Timothy":            { author: "Paul",                 location: "Macedonia",         date: "c. AD 63–65"  },
  "II Timothy":           { author: "Paul",                 location: "Rome",              date: "c. AD 67"     },
  "Titus":                { author: "Paul",                 location: "Macedonia",         date: "c. AD 63–65"  },
  "Philemon":             { author: "Paul",                 location: "Rome",              date: "c. AD 62"     },
  "Hebrews":              { author: "Unknown",              location: "Rome / Jerusalem",  date: "c. AD 64–70"  },
  "James":                { author: "James",                location: "Jerusalem",         date: "c. AD 45–50"  },
  "I Peter":              { author: "Peter",                location: "Rome (Babylon)",    date: "c. AD 64–68"  },
  "II Peter":             { author: "Peter",                location: "Rome",              date: "c. AD 65–68"  },
  "I John":               { author: "John the Apostle",     location: "Ephesus",           date: "c. AD 90–95"  },
  "II John":              { author: "John the Apostle",     location: "Ephesus",           date: "c. AD 90–95"  },
  "III John":             { author: "John the Apostle",     location: "Ephesus",           date: "c. AD 90–95"  },
  "Jude":                 { author: "Jude",                 location: "Palestine",         date: "c. AD 65–80"  },
  "Revelation of John":   { author: "John the Apostle",     location: "Patmos",            date: "c. AD 95"     },
};
